var _bounding_rectangle_human_readable_converter_8cs =
[
    [ "Engine.Serialization.BoundingRectangleHumanReadableConverter", "class_engine_1_1_serialization_1_1_bounding_rectangle_human_readable_converter.html", "class_engine_1_1_serialization_1_1_bounding_rectangle_human_readable_converter" ]
];