var dir_1f8d5a022218767e6dfb00698735ed73 =
[
    [ "AudioManager.cs", "_audio_manager_8cs.html", "_audio_manager_8cs" ],
    [ "BlocksTexturesManager.cs", "_blocks_textures_manager_8cs.html", "_blocks_textures_manager_8cs" ],
    [ "CharacterSkinsManager.cs", "_character_skins_manager_8cs.html", "_character_skins_manager_8cs" ],
    [ "ClipboardManager.cs", "_clipboard_manager_8cs.html", "_clipboard_manager_8cs" ],
    [ "CommunityContentManager.cs", "_community_content_manager_8cs.html", "_community_content_manager_8cs" ],
    [ "DialogsManager.cs", "_dialogs_manager_8cs.html", "_dialogs_manager_8cs" ],
    [ "ExceptionManager.cs", "_exception_manager_8cs.html", "_exception_manager_8cs" ],
    [ "ExternalContentManager.cs", "_external_content_manager_8cs.html", "_external_content_manager_8cs" ],
    [ "FurniturePacksManager.cs", "_furniture_packs_manager_8cs.html", "_furniture_packs_manager_8cs" ],
    [ "GameManager.cs", "_game_manager_8cs.html", "_game_manager_8cs" ],
    [ "HardwareManager.cs", "_hardware_manager_8cs.html", "_hardware_manager_8cs" ],
    [ "InstancedModelsManager.cs", "_instanced_models_manager_8cs.html", "_instanced_models_manager_8cs" ],
    [ "KeyCompatibleGroupsManager.cs", "_key_compatible_groups_manager_8cs.html", "_key_compatible_groups_manager_8cs" ],
    [ "LightingManager.cs", "_lighting_manager_8cs.html", "_lighting_manager_8cs" ],
    [ "MarketplaceManager.cs", "_marketplace_manager_8cs.html", "_marketplace_manager_8cs" ],
    [ "MotdManager.cs", "_motd_manager_8cs.html", "_motd_manager_8cs" ],
    [ "MusicManager.cs", "_music_manager_8cs.html", "_music_manager_8cs" ],
    [ "PerformanceManager.cs", "_performance_manager_8cs.html", "_performance_manager_8cs" ],
    [ "PlantsManager.cs", "_plants_manager_8cs.html", "_plants_manager_8cs" ],
    [ "ProgressManager.cs", "_progress_manager_8cs.html", "_progress_manager_8cs" ],
    [ "ScreenCaptureManager.cs", "_screen_capture_manager_8cs.html", "_screen_capture_manager_8cs" ],
    [ "ScreenResolutionManager.cs", "_screen_resolution_manager_8cs.html", "_screen_resolution_manager_8cs" ],
    [ "ScreensManager.cs", "_screens_manager_8cs.html", "_screens_manager_8cs" ],
    [ "SettingsManager.cs", "_settings_manager_8cs.html", "_settings_manager_8cs" ],
    [ "StringsManager.cs", "_strings_manager_8cs.html", "_strings_manager_8cs" ],
    [ "UserManager.cs", "_user_manager_8cs.html", "_user_manager_8cs" ],
    [ "VersionsManager.cs", "_versions_manager_8cs.html", "_versions_manager_8cs" ],
    [ "VrManager.cs", "_vr_manager_8cs.html", "_vr_manager_8cs" ],
    [ "WebBrowserManager.cs", "_web_browser_manager_8cs.html", "_web_browser_manager_8cs" ],
    [ "WebManager.cs", "_web_manager_8cs.html", "_web_manager_8cs" ],
    [ "WindowsRegisterManager.cs", "_windows_register_manager_8cs.html", null ],
    [ "WorldsManager.cs", "_worlds_manager_8cs.html", "_worlds_manager_8cs" ]
];