var namespace_engine_1_1_serialization =
[
    [ "Archive", "class_engine_1_1_serialization_1_1_archive.html", "class_engine_1_1_serialization_1_1_archive" ],
    [ "ArraySerializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_array_serializer-1-g.html", "class_engine_1_1_serialization_1_1_array_serializer-1-g" ],
    [ "BinaryInputArchive", "class_engine_1_1_serialization_1_1_binary_input_archive.html", "class_engine_1_1_serialization_1_1_binary_input_archive" ],
    [ "BinaryOutputArchive", "class_engine_1_1_serialization_1_1_binary_output_archive.html", "class_engine_1_1_serialization_1_1_binary_output_archive" ],
    [ "BlendStateHumanReadableConverter", "class_engine_1_1_serialization_1_1_blend_state_human_readable_converter.html", "class_engine_1_1_serialization_1_1_blend_state_human_readable_converter" ],
    [ "BooleanHumanReadableConverter", "class_engine_1_1_serialization_1_1_boolean_human_readable_converter.html", "class_engine_1_1_serialization_1_1_boolean_human_readable_converter" ],
    [ "BooleanSerializer", "class_engine_1_1_serialization_1_1_boolean_serializer.html", "class_engine_1_1_serialization_1_1_boolean_serializer" ],
    [ "BoundingBoxHumanReadableConverter", "class_engine_1_1_serialization_1_1_bounding_box_human_readable_converter.html", "class_engine_1_1_serialization_1_1_bounding_box_human_readable_converter" ],
    [ "BoundingCircleHumanReadableConverter", "class_engine_1_1_serialization_1_1_bounding_circle_human_readable_converter.html", "class_engine_1_1_serialization_1_1_bounding_circle_human_readable_converter" ],
    [ "BoundingRectangleHumanReadableConverter", "class_engine_1_1_serialization_1_1_bounding_rectangle_human_readable_converter.html", "class_engine_1_1_serialization_1_1_bounding_rectangle_human_readable_converter" ],
    [ "BoundingSphereHumanReadableConverter", "class_engine_1_1_serialization_1_1_bounding_sphere_human_readable_converter.html", "class_engine_1_1_serialization_1_1_bounding_sphere_human_readable_converter" ],
    [ "BoxHumanReadableConverter", "class_engine_1_1_serialization_1_1_box_human_readable_converter.html", "class_engine_1_1_serialization_1_1_box_human_readable_converter" ],
    [ "BoxSerializer", "class_engine_1_1_serialization_1_1_box_serializer.html", "class_engine_1_1_serialization_1_1_box_serializer" ],
    [ "ByteHumanReadableConverter", "class_engine_1_1_serialization_1_1_byte_human_readable_converter.html", "class_engine_1_1_serialization_1_1_byte_human_readable_converter" ],
    [ "ByteSerializer", "class_engine_1_1_serialization_1_1_byte_serializer.html", "class_engine_1_1_serialization_1_1_byte_serializer" ],
    [ "CharHumanReadableConverter", "class_engine_1_1_serialization_1_1_char_human_readable_converter.html", "class_engine_1_1_serialization_1_1_char_human_readable_converter" ],
    [ "CharSerializer", "class_engine_1_1_serialization_1_1_char_serializer.html", "class_engine_1_1_serialization_1_1_char_serializer" ],
    [ "ColorHumanReadableConverter", "class_engine_1_1_serialization_1_1_color_human_readable_converter.html", "class_engine_1_1_serialization_1_1_color_human_readable_converter" ],
    [ "ColorSerializer", "class_engine_1_1_serialization_1_1_color_serializer.html", "class_engine_1_1_serialization_1_1_color_serializer" ],
    [ "DateTimeHumanReadableConverter", "class_engine_1_1_serialization_1_1_date_time_human_readable_converter.html", "class_engine_1_1_serialization_1_1_date_time_human_readable_converter" ],
    [ "DecimalHumanReadableConverter", "class_engine_1_1_serialization_1_1_decimal_human_readable_converter.html", "class_engine_1_1_serialization_1_1_decimal_human_readable_converter" ],
    [ "DictionarySerializer&lt; K, V &gt;", "class_engine_1_1_serialization_1_1_dictionary_serializer-2-g.html", "class_engine_1_1_serialization_1_1_dictionary_serializer-2-g" ],
    [ "DoubleHumanReadableConverter", "class_engine_1_1_serialization_1_1_double_human_readable_converter.html", "class_engine_1_1_serialization_1_1_double_human_readable_converter" ],
    [ "DoubleSerializer", "class_engine_1_1_serialization_1_1_double_serializer.html", "class_engine_1_1_serialization_1_1_double_serializer" ],
    [ "DynamicArraySerializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_dynamic_array_serializer-1-g.html", "class_engine_1_1_serialization_1_1_dynamic_array_serializer-1-g" ],
    [ "EngineBinaryReader", "class_engine_1_1_serialization_1_1_engine_binary_reader.html", "class_engine_1_1_serialization_1_1_engine_binary_reader" ],
    [ "EngineBinaryWriter", "class_engine_1_1_serialization_1_1_engine_binary_writer.html", "class_engine_1_1_serialization_1_1_engine_binary_writer" ],
    [ "Enum32Serializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_enum32_serializer-1-g.html", "class_engine_1_1_serialization_1_1_enum32_serializer-1-g" ],
    [ "Enum64Serializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_enum64_serializer-1-g.html", "class_engine_1_1_serialization_1_1_enum64_serializer-1-g" ],
    [ "EnumHumanReadableConverter", "class_engine_1_1_serialization_1_1_enum_human_readable_converter.html", "class_engine_1_1_serialization_1_1_enum_human_readable_converter" ],
    [ "GuidHumanReadableConverter", "class_engine_1_1_serialization_1_1_guid_human_readable_converter.html", "class_engine_1_1_serialization_1_1_guid_human_readable_converter" ],
    [ "GuidSerializer", "class_engine_1_1_serialization_1_1_guid_serializer.html", "class_engine_1_1_serialization_1_1_guid_serializer" ],
    [ "HashSetSerializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_hash_set_serializer-1-g.html", "class_engine_1_1_serialization_1_1_hash_set_serializer-1-g" ],
    [ "HumanReadableConverter", "class_engine_1_1_serialization_1_1_human_readable_converter.html", "class_engine_1_1_serialization_1_1_human_readable_converter" ],
    [ "HumanReadableConverterAttribute", "class_engine_1_1_serialization_1_1_human_readable_converter_attribute.html", "class_engine_1_1_serialization_1_1_human_readable_converter_attribute" ],
    [ "IHumanReadableConverter", "interface_engine_1_1_serialization_1_1_i_human_readable_converter.html", "interface_engine_1_1_serialization_1_1_i_human_readable_converter" ],
    [ "InputArchive", "class_engine_1_1_serialization_1_1_input_archive.html", "class_engine_1_1_serialization_1_1_input_archive" ],
    [ "Int16HumanReadableConverter", "class_engine_1_1_serialization_1_1_int16_human_readable_converter.html", "class_engine_1_1_serialization_1_1_int16_human_readable_converter" ],
    [ "Int16Serializer", "class_engine_1_1_serialization_1_1_int16_serializer.html", "class_engine_1_1_serialization_1_1_int16_serializer" ],
    [ "Int32HumanReadableConverter", "class_engine_1_1_serialization_1_1_int32_human_readable_converter.html", "class_engine_1_1_serialization_1_1_int32_human_readable_converter" ],
    [ "Int32Serializer", "class_engine_1_1_serialization_1_1_int32_serializer.html", "class_engine_1_1_serialization_1_1_int32_serializer" ],
    [ "Int64HumanReadableConverter", "class_engine_1_1_serialization_1_1_int64_human_readable_converter.html", "class_engine_1_1_serialization_1_1_int64_human_readable_converter" ],
    [ "Int64Serializer", "class_engine_1_1_serialization_1_1_int64_serializer.html", "class_engine_1_1_serialization_1_1_int64_serializer" ],
    [ "ISerializable", "interface_engine_1_1_serialization_1_1_i_serializable.html", "interface_engine_1_1_serialization_1_1_i_serializable" ],
    [ "ISerializer&lt; T &gt;", "interface_engine_1_1_serialization_1_1_i_serializer-1-g.html", "interface_engine_1_1_serialization_1_1_i_serializer-1-g" ],
    [ "KeyValuePairSerializer&lt; K, V &gt;", "class_engine_1_1_serialization_1_1_key_value_pair_serializer-2-g.html", "class_engine_1_1_serialization_1_1_key_value_pair_serializer-2-g" ],
    [ "ListSerializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_list_serializer-1-g.html", "class_engine_1_1_serialization_1_1_list_serializer-1-g" ],
    [ "MatrixHumanReadableConverter", "class_engine_1_1_serialization_1_1_matrix_human_readable_converter.html", "class_engine_1_1_serialization_1_1_matrix_human_readable_converter" ],
    [ "MatrixSerializer", "class_engine_1_1_serialization_1_1_matrix_serializer.html", "class_engine_1_1_serialization_1_1_matrix_serializer" ],
    [ "NullableSerializer&lt; T &gt;", "class_engine_1_1_serialization_1_1_nullable_serializer-1-g.html", "class_engine_1_1_serialization_1_1_nullable_serializer-1-g" ],
    [ "OutputArchive", "class_engine_1_1_serialization_1_1_output_archive.html", "class_engine_1_1_serialization_1_1_output_archive" ],
    [ "PlaneHumanReadableConverter", "class_engine_1_1_serialization_1_1_plane_human_readable_converter.html", "class_engine_1_1_serialization_1_1_plane_human_readable_converter" ],
    [ "PlaneSerializer", "class_engine_1_1_serialization_1_1_plane_serializer.html", "class_engine_1_1_serialization_1_1_plane_serializer" ],
    [ "Point2HumanReadableConverter", "class_engine_1_1_serialization_1_1_point2_human_readable_converter.html", "class_engine_1_1_serialization_1_1_point2_human_readable_converter" ],
    [ "Point2Serializer", "class_engine_1_1_serialization_1_1_point2_serializer.html", "class_engine_1_1_serialization_1_1_point2_serializer" ],
    [ "Point3HumanReadableConverter", "class_engine_1_1_serialization_1_1_point3_human_readable_converter.html", "class_engine_1_1_serialization_1_1_point3_human_readable_converter" ],
    [ "Point3Serializer", "class_engine_1_1_serialization_1_1_point3_serializer.html", "class_engine_1_1_serialization_1_1_point3_serializer" ],
    [ "QuaternionHumanReadableConverter", "class_engine_1_1_serialization_1_1_quaternion_human_readable_converter.html", "class_engine_1_1_serialization_1_1_quaternion_human_readable_converter" ],
    [ "QuaternionSerializer", "class_engine_1_1_serialization_1_1_quaternion_serializer.html", "class_engine_1_1_serialization_1_1_quaternion_serializer" ],
    [ "RectangleHumanReadableConverter", "class_engine_1_1_serialization_1_1_rectangle_human_readable_converter.html", "class_engine_1_1_serialization_1_1_rectangle_human_readable_converter" ],
    [ "RectangleSerializer", "class_engine_1_1_serialization_1_1_rectangle_serializer.html", "class_engine_1_1_serialization_1_1_rectangle_serializer" ],
    [ "SByteSerializer", "class_engine_1_1_serialization_1_1_s_byte_serializer.html", "class_engine_1_1_serialization_1_1_s_byte_serializer" ],
    [ "SerializationOptionsAttribute", "class_engine_1_1_serialization_1_1_serialization_options_attribute.html", "class_engine_1_1_serialization_1_1_serialization_options_attribute" ],
    [ "SingleHumanReadableConverter", "class_engine_1_1_serialization_1_1_single_human_readable_converter.html", "class_engine_1_1_serialization_1_1_single_human_readable_converter" ],
    [ "SingleSerializer", "class_engine_1_1_serialization_1_1_single_serializer.html", "class_engine_1_1_serialization_1_1_single_serializer" ],
    [ "SortedDictionarySerializer&lt; K, V &gt;", "class_engine_1_1_serialization_1_1_sorted_dictionary_serializer-2-g.html", "class_engine_1_1_serialization_1_1_sorted_dictionary_serializer-2-g" ],
    [ "SortedListSerializer&lt; K, V &gt;", "class_engine_1_1_serialization_1_1_sorted_list_serializer-2-g.html", "class_engine_1_1_serialization_1_1_sorted_list_serializer-2-g" ],
    [ "StringHumanReadableConverter", "class_engine_1_1_serialization_1_1_string_human_readable_converter.html", "class_engine_1_1_serialization_1_1_string_human_readable_converter" ],
    [ "StringSerializer", "class_engine_1_1_serialization_1_1_string_serializer.html", "class_engine_1_1_serialization_1_1_string_serializer" ],
    [ "SystemDrawingTypesConverters", "class_engine_1_1_serialization_1_1_system_drawing_types_converters.html", "class_engine_1_1_serialization_1_1_system_drawing_types_converters" ],
    [ "TypeCache", "class_engine_1_1_serialization_1_1_type_cache.html", "class_engine_1_1_serialization_1_1_type_cache" ],
    [ "UInt16HumanReadableConverter", "class_engine_1_1_serialization_1_1_u_int16_human_readable_converter.html", "class_engine_1_1_serialization_1_1_u_int16_human_readable_converter" ],
    [ "UInt16Serializer", "class_engine_1_1_serialization_1_1_u_int16_serializer.html", "class_engine_1_1_serialization_1_1_u_int16_serializer" ],
    [ "UInt32HumanReadableConverter", "class_engine_1_1_serialization_1_1_u_int32_human_readable_converter.html", "class_engine_1_1_serialization_1_1_u_int32_human_readable_converter" ],
    [ "UInt32Serializer", "class_engine_1_1_serialization_1_1_u_int32_serializer.html", "class_engine_1_1_serialization_1_1_u_int32_serializer" ],
    [ "UInt64HumanReadableConverter", "class_engine_1_1_serialization_1_1_u_int64_human_readable_converter.html", "class_engine_1_1_serialization_1_1_u_int64_human_readable_converter" ],
    [ "UInt64Serializer", "class_engine_1_1_serialization_1_1_u_int64_serializer.html", "class_engine_1_1_serialization_1_1_u_int64_serializer" ],
    [ "Vector2HumanReadableConverter", "class_engine_1_1_serialization_1_1_vector2_human_readable_converter.html", "class_engine_1_1_serialization_1_1_vector2_human_readable_converter" ],
    [ "Vector2Serializer", "class_engine_1_1_serialization_1_1_vector2_serializer.html", "class_engine_1_1_serialization_1_1_vector2_serializer" ],
    [ "Vector3HumanReadableConverter", "class_engine_1_1_serialization_1_1_vector3_human_readable_converter.html", "class_engine_1_1_serialization_1_1_vector3_human_readable_converter" ],
    [ "Vector3Serializer", "class_engine_1_1_serialization_1_1_vector3_serializer.html", "class_engine_1_1_serialization_1_1_vector3_serializer" ],
    [ "Vector4HumanReadableConverter", "class_engine_1_1_serialization_1_1_vector4_human_readable_converter.html", "class_engine_1_1_serialization_1_1_vector4_human_readable_converter" ],
    [ "Vector4Serializer", "class_engine_1_1_serialization_1_1_vector4_serializer.html", "class_engine_1_1_serialization_1_1_vector4_serializer" ],
    [ "VersionHumanReadableConverter", "class_engine_1_1_serialization_1_1_version_human_readable_converter.html", "class_engine_1_1_serialization_1_1_version_human_readable_converter" ],
    [ "XElementSerializer", "class_engine_1_1_serialization_1_1_x_element_serializer.html", "class_engine_1_1_serialization_1_1_x_element_serializer" ],
    [ "XmlInputArchive", "class_engine_1_1_serialization_1_1_xml_input_archive.html", "class_engine_1_1_serialization_1_1_xml_input_archive" ],
    [ "XmlOutputArchive", "class_engine_1_1_serialization_1_1_xml_output_archive.html", "class_engine_1_1_serialization_1_1_xml_output_archive" ],
    [ "AutoConstructMode", "namespace_engine_1_1_serialization.html#ab2363e81138e903f831062d921c9307d", [
      [ "NotSet", "namespace_engine_1_1_serialization.html#ab2363e81138e903f831062d921c9307dafaf396cbd83927b72a84d2616fac76ff", null ],
      [ "No", "namespace_engine_1_1_serialization.html#ab2363e81138e903f831062d921c9307dabafd7322c6e97d25b6299b5d6fe8920b", null ],
      [ "Yes", "namespace_engine_1_1_serialization.html#ab2363e81138e903f831062d921c9307da93cba07454f06a4a960172bbd6e2a435", null ]
    ] ]
];